//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SafePlaceDbContextt : DbContext
    {
        public SafePlaceDbContextt()
            : base("name=SafePlaceDbContextt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblFile> TblFiles { get; set; }
        public virtual DbSet<TblFileType> TblFileTypes { get; set; }
        public virtual DbSet<TblPatient> TblPatients { get; set; }
        public virtual DbSet<TblRoom> TblRooms { get; set; }
        public virtual DbSet<TblSummary> TblSummaries { get; set; }
        public virtual DbSet<TblTherapist> TblTherapists { get; set; }
        public virtual DbSet<TblTreatment> TblTreatments { get; set; }
        public virtual DbSet<TblTreat> TblTreats { get; set; }
        public virtual DbSet<TblType> TblTypes { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<TblWrittenFor> TblWrittenFors { get; set; }
    }
}
