//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDaysoff
    {
        public int Request_Id { get; set; }
        public string Therapist_Id { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Dayoff { get; set; }
    
        public virtual TblTherapist TblTherapist { get; set; }
    }
}
