//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFile()
        {
            this.TblFills = new HashSet<TblFills>();
        }
    
        public int File_Num { get; set; }
        public System.DateTime DateSent { get; set; }
        public int FileType_Num { get; set; }
        public byte[] Content { get; set; }
        public string File_name { get; set; }
        public Nullable<int> Id { get; set; }
        public string FilePath { get; set; }
    
        public virtual TblUsers TblUsers { get; set; }
        public virtual TblFileType TblFileType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFills> TblFills { get; set; }
    }
}
