//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSummary()
        {
            this.TblWrittenFor = new HashSet<TblWrittenFor>();
        }
    
        public int Summary_Num { get; set; }
        public string WrittenBy { get; set; }
        public string Content { get; set; }
        public System.DateTime Summary_Date { get; set; }
        public string ImportentToNote { get; set; }
        public string WrittenById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWrittenFor> TblWrittenFor { get; set; }
    }
}
