//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTreatment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTreatment()
        {
            this.TblTreats = new HashSet<TblTreat>();
            this.TblWrittenFors = new HashSet<TblWrittenFor>();
        }
    
        public int Treatment_Id { get; set; }
        public System.DateTime Treatment_Date { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string WasDone { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public Nullable<int> Room_Num { get; set; }
    
        public virtual TblRoom TblRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTreat> TblTreats { get; set; }
        public virtual TblType TblType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWrittenFor> TblWrittenFors { get; set; }
    }
}
